[config]
schemaVersion = "0.0.1"

[package]
namespace = "Inject0r77"
name = "Inject0rHUD"
versionNumber = "0.5.7"
description = "Client-side Valheim HUD with production hover timers, positive-effect timers, profiles, durability, FPS/Ping widgets."
websiteUrl = "https://github.com/Inject0r77/Inject0rHud-Valheim"
containsNsfwContent = false

[package.dependencies]
denikson-BepInExPack_Valheim = "5.4.2350"

[build]
icon = "./icon.png"
readme = "./README.md"
outdir = "./dist"

[[build.copy]]
source = "./bin/Release/Inject0rHUD.dll"
target = "plugins/Inject0rHUD.dll"

[[build.copy]]
source = "./CHANGELOG.md"
target = "CHANGELOG.md"
